// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thfalxtopjlgpoiadcmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoZmFseHRvcGpsZ3BvaWFkY210Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MTU2MTYsImV4cCI6MjA3MTE5MTYxNn0.aqK-oX4hYRZaIriLdvot3-esbEsXDT5_b19gTJOk6Ek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});